USE casedb;

DROP TABLE IF EXISTS Space;
DROP TABLE IF EXISTS building;
DROP TABLE IF EXISTS campus;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS Requirement;
DROP TABLE IF EXISTS Program;
DROP TABLE IF EXISTS Department;
