use casedb;

/* PROCEDURES */
DROP PROCEDURE IF EXISTS abortAllocation;
DROP PROCEDURE IF EXISTS startAllocation;
DROP PROCEDURE IF EXISTS resetAllocation;
DROP PROCEDURE IF EXISTS allocateSpace;
DROP PROCEDURE IF EXISTS prioritizeSubjects;
DROP PROCEDURE IF EXISTS setSuitableRooms;
DROP PROCEDURE IF EXISTS LogAllocation;

/* FUNCTIONS */
DROP FUNCTION IF EXISTS getMissingItemAmount;
