USE casedb;

DROP TABLE IF EXISTS ´Space´;
DROP TABLE IF EXISTS Building;
DROP TABLE IF EXISTS Campus;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS Requirement;
DROP TABLE IF EXISTS Program;
DROP TABLE IF EXISTS Department;
