CREATE DATABASE IF NOT EXISTS siba;
USE siba;

-- Department / aineryhmä
CREATE TABLE IF NOT EXISTS department (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Program / pääaine
CREATE TABLE IF NOT EXISTS program (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    department_id INT UNSIGNED,
    CONSTRAINT FOREIGN KEY (department_id) REFERENCES department(id)
    	ON DELETE NO ACTION
    	ON UPDATE CASCADE
);

-- Requirement / Vaatimus
CREATE TABLE IF NOT EXISTS requirement (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Equipment / varuste
CREATE TABLE IF NOT EXISTS equipment (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Campus / Kampus
CREATE TABLE IF NOT EXISTS campus (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Building / Rakennus
CREATE TABLE IF NOT EXISTS building (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Space / Tila
CREATE TABLE IF NOT EXISTS space (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    room_size SMALLINT UNSIGNED,
    people_capasity SMALLINT UNSIGNED,
    building_id INT UNSIGNED NOT NULL,
    CONSTRAINT fk_space_building
    	FOREIGN KEY (building_id) REFERENCES building(id)
    	ON DELETE CASCADE
    	ON UPDATE CASCADE
);


