SELECT * FROM casedb.Department;
SELECT * FROM casedb.Program;
SELECT * FROM casedb.Subject;
SELECT * FROM casedb.Requirement;
SELECT * FROM casedb.Equipment;
SELECT * FROM Space;
SELECT * FROM SpaceEquipment;
SELECT * FROM User;
SELECT * FROM DepartmentPlanner;