SELECT * FROM siba.department;
SELECT * FROM siba.program;
SELECT * FROM siba.subject;
SELECT * FROM siba.requirement;
SELECT * FROM siba.equipment;
SELECT * FROM space;
SELECT * FROM spaces_equipment;
SELECT * FROM user;
SELECT * FROM users_departments;