USE casedb;

DELETE FROM AllocCurrentRoundUser;

DELETE FROM AllocSpace;

DELETE FROM AllocSubject;
ALTER TABLE AllocSubject AUTO_INCREMENT=90001;

DELETE FROM AllocRound;
ALTER TABLE AllocRound AUTO_INCREMENT=10001;

DELETE FROM SpaceDepartment;
ALTER TABLE SpaceDepartment AUTO_INCREMENT=20001;

DELETE FROM SubjectEquipment;

DELETE FROM `Subject`;
ALTER TABLE `Subject` AUTO_INCREMENT=4001;

DELETE FROM Program;
ALTER TABLE Program AUTO_INCREMENT=3001;

DELETE FROM SpaceEquipment;
ALTER TABLE SpaceEquipment AUTO_INCREMENT=20001;

DELETE FROM Equipment;
ALTER TABLE Equipment AUTO_INCREMENT=2001;

DELETE FROM `Space`;
ALTER TABLE `Space` AUTO_INCREMENT=1001;

DELETE FROM `SubjectType`;
ALTER TABLE `SubjectType` AUTO_INCREMENT=801;

DELETE FROM Building;
ALTER TABLE Building AUTO_INCREMENT=401;

DELETE FROM Campus;
ALTER TABLE Campus AUTO_INCREMENT=301;

DELETE FROM DepartmentPlanner;

DELETE FROM `User`;
ALTER TABLE `User` AUTO_INCREMENT=201;

DELETE FROM Department;
ALTER TABLE Department AUTO_INCREMENT=101;

DELETE FROM GlobalSetting;
ALTER TABLE GlobalSetting AUTO_INCREMENT=1;