### Remember to select the proper rest client environment

### Reset database before performing other tests
GET {{host}}/resetDatabase
Authorization: Basic {{token}}

@nextId = 404

### Get all
GET {{host}}/building
Authorization: Basic {{token}}

### Get one by id
GET {{host}}/building/401
Authorization: Basic {{token}}

### Create one
POST {{host}}/building
Authorization: Basic {{token}}
Content-Type: application/json

{
    "name": "XYZ-building",
    "description": "Sibeliusakatemian muu rakennus"
}

### Create one without description
POST {{host}}/building
Authorization: Basic {{token}}
Content-Type: application/json

{
    "name": "No desc building"
}

### Create one without description
POST {{host}}/building
Authorization: Basic {{token}}
Content-Type: application/json

{
    "name": "No desc building 3",
    "description": "  "
}

### Get all
GET {{host}}/building
Authorization: Basic {{token}}

### Create multi
POST {{host}}/building/multi
Authorization: Basic {{token}}
Content-Type: application/json

[
    {
    "name": "XYgdfG",
    "description": "Sibeliusakatemian toinen rakennus"
    },

    {
    "name": "MNfdO"
    }
]

### Get all
GET {{host}}/building
Authorization: Basic {{token}}

### Update one
PUT {{host}}/building
Authorization: Basic {{token}}
Content-Type: application/json

{
    "id": {{nextId}},
    "name": "YYY",
    "description": "Sibeliusakatemian sivurakennus"
}

### Get one by id
GET {{host}}/building/{{nextId}}
Authorization: Basic {{token}}

### Delete one
DELETE {{host}}/building/{{nextId}}
Authorization: Basic {{token}}

### Get one by id
GET {{host}}/building/{{nextId}}
Authorization: Basic {{token}}
