### token to
### root root root folder's .vscode folder's settings.json file 

### 1. Get all   - L
GET {{host}}/setting
Authorization: Basic {{token}}

### next id after Testdata Reset:
@nextId=16

### 2. Get one by id   -  R
GET {{host}}/setting/1
Authorization: Basic {{token}}

### 3. Possibly other gets    -  L?R?

### 4. Post a new one    -   C
POST {{host}}/setting/
Authorization: Basic {{token}}
Content-Type: application/json

{
  "name": "test setting xyz1234567",
  "description": "Setting for just Rest api test case",
  "numberValue": 555,
  "textValue": "Hello"
}

### 5. Update existing one  -   U
### // id now removed from PUT URL! It's in JSON data
PUT {{host}}/setting/         
Authorization: Basic {{token}}
Content-Type: application/json

{
  "id": {{nextId}},
  "name": "Changed name here",
  "description": "fasdfasdfasdf sdfsadf",
  "numberValue": 456,
  "textValue": null
}

###
GET {{host}}/setting/{{nextId}}
Authorization: Basic {{token}}

### 6. Delete one by id    -  D
DELETE {{host}}/setting/{{nextId}}
Authorization: Basic {{token}}

###
GET {{host}}/setting/{{nextId}}
Authorization: Basic {{token}}
