### Remember to select the proper rest client environment
### Note: there's no PUT or DELETE in program.ts

### 1. Get a list of all programs (ids and names)
GET {{host}}/program
Authorization: Basic {{token}}

### 2. Get a program by it's id (id, name, and department id)
GET {{host}}/program/3030
Authorization: Basic {{token}}

### 3. Get program name(s) by user id
GET {{host}}/program/userprograms/203
Authorization: Basic {{token}}

### next id after TestData reset
@nextId=3031

### 4. Create new program
POST {{host}}/program
Authorization: Basic {{token}}
Content-Type: application/json

{
    "name": "Test 1",
    "departmentId" : "101"
}

###
GET {{host}}/program/{{nextId}}
Authorization: Basic {{token}}

### 5. Update an existing program
PUT {{host}}/program/
Authorization: Basic {{token}}
Content-Type: application/json

{
    "id": {{nextId}},
    "name": "Edited test 1",
    "departmentId": 102
}

###
GET {{host}}/program/{{nextId}}
Authorization: Basic {{token}}

### 7. Delete a program
DELETE {{host}}/program/{{nextId}}
Authorization: Basic {{token}}

###
GET {{host}}/program/{{nextId}}
Authorization: Basic {{token}}

###
GET {{host}}/program/{{nextId}}/numberOfLessons
Authorization: Basic {{token}}