GET {{host}}/spaceequipment/getEquipment/1020
Authorization: Basic {{token}}

###
POST {{host}}/spaceequipment/post
Authorization: Basic {{token}}
Content-Type: application/json

{
  "spaceId": 1020,
  "equipmentId": 2028
}

###
DELETE {{host}}/spaceequipment/delete/1020/2028
Authorization: Basic {{token}}