name: dbbe_deploy_project

services:
  siba_db_deployment:
    image: mariadb:latest
    container_name: siba_db_container
    env_file:
      - .env.db
      - .env.db.root
      - .env.network
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./Database/SQL_Scripts/000__CreateALLdb.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - db_be_network

  siba_be_deployment:
    container_name: siba_be_container
    build: .
    env_file: 
     - .env.be
     - .env.db
     - .env.network
    depends_on:
      - siba_db_deployment
    environment:
      - DB_HOST=siba_db_deployment
    ports:
      - '${BE_SERVER_PORT}:${BE_SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_be_network

  siba_be_reverseproxy:
    env_file: .env
    image: nginx:alpine
    container_name: siba_be_reverse_proxy_container
    depends_on:
      - siba_be_deployment
    ports:
      - "3000:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - "${SSL_CERT_PATH}:/etc/nginx/ssl/fullchain.pem"
      - "${SSL_KEY_PATH}:/etc/nginx/ssl/privkey.pem"
    networks:
      - db_be_network

networks:
  db_be_network:
    driver: bridge

volumes:
  mariadb_data: