-- Program, Department, DepartmentPlanner, User (roolit: isAdmin)

CREATE TABLE IF NOT EXISTS `Department` (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `User` (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  isAdmin BOOLEAN NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `Program` (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  departmentId INTEGER,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (departmentId) REFERENCES Department (id) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `DepartmentPlanner` (
  id INTEGER NOT NULL AUTO_INCREMENT,
  departmentId INTEGER,
  userId INTEGER,
  PRIMARY KEY (id),
  CONSTRAINT FOREIGN KEY (departmentId) REFERENCES Department (id) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION,
  CONSTRAINT FOREIGN KEY (userId) REFERENCES User (id) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION
);